const ApplicationData = [
  {
    id: 1,
    title: "Filtersorb",
    children: [
      {
        id: 1,
        title: "Nucleation Assisted Crystallization",
        image: "/assets/img/menubar/product7.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Food & Water Application’s",
        image: "/assets/img/menubar/product7.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Temporary Hardness Treatment",
        image: "/assets/img/menubar/product7.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Permanent Hardness Treatment",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Scale Prevention",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Boiler Water Treatment",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Heat Exchangers",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Filtersorb System’s",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Filtersorb System Design",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Blowdown & Scale Prevention",
        image: "/assets/img/menubar/product7.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  {
    id: 2,
    title: "Oxy Treatment",
    children: [
      {
        id: 1,
        title: "Oxidation of Bacteria & Viruses",
        image: "/assets/img/menubar/product8.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Oxidation of Inorganic Compounds",
        image: "/assets/img/menubar/product8.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Reduction of Inorganics Compounds",
        image: "/assets/img/menubar/product8.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Oxidation of Ammonium",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Heavy Metals Removal via Oxidation",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Removal of Dyes, fatty acids, benzene, chlorine through Oxidation",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Methane Removal from Lakes through Strong Oxidation",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Oxidation of Landfill Leachate",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Oxygen Production for both Oxycline and in the anoxic bottom Layers of Lakes via Catalytic Reaction",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Oxygen Production for Aquaculture Pond Health",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 11,
        title: "Treatment of any Waste Water with Advanced Oxidation Process",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 12,
        title: "Sewage Reuse for Irrigation after RedOxy-3C Treatment",
        image: "/assets/img/menubar/product8.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  {
    id: 3,
    title: "Filtration",
    children: [
      {
        id: 1,
        title: "Iron & Manganese Removal",
        image: "/assets/img/menubar/product9.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Radionuclide Removal",
        image: "/assets/img/menubar/product9.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Turbidity Removal",
        image: "/assets/img/menubar/product9.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Hydrogen Sulfide Removal",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Heavy Metal’s Removal",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Suspended Solids Removal",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Food & Water Applications",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Drinking Water Treatment",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Boiler Water Treatment",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Heat Exchangers",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 11,
        title: "Cooling Water Treatment",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 12,
        title: "Waste Water Treatment",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 13,
        title: "Hydro Carbon Processing",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 14,
        title: "Waste Water Treatment",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 15,
        title: "Zero Liquid Discharge",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 16,
        title: "Water Reuse",
        image: "/assets/img/menubar/product9.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  {
    id: 4,
    title: "Adsorbtion",
    children: [
      {
        id: 1,
        title: "Aluminum",
        image: "/assets/img/menubar/product10.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Ammonia",
        image: "/assets/img/menubar/product10.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Arsenic",
        image: "/assets/img/menubar/product10.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Barium",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Cadmium",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Chloramine & Chloramines Removal",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Scale Prevention",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Corrosion Prevention",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Antimicrobial Treatment",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Food & Water Industries",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 11,
        title: "Food Protection",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 12,
        title: "Water Recycling Systems",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 13,
        title: "Catalyst Materials",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 14,
        title: "Cleaning & Passivation Process in Drinking Water System",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 15,
        title: "Heating Equipment",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 16,
        title: "Boiler Water Treatment",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 16,
        title: "Closed Loop Equipment",
        image: "/assets/img/menubar/product10.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  {
    id: 5,
    title: "Water Reuse",
    children: [
      {
        id: 1,
        title: "Zero Liquid Discharge Operations",
        image: "/assets/img/menubar/product11.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Reduction of Sludge",
        image: "/assets/img/menubar/product11.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Cooling Blowdown Reduction",
        image: "/assets/img/menubar/product11.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Phosphorus Free Antiscalants for Membrane Filtration",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Scale Prevention without using Salts Chemical",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Precipitation of Healthy Metals",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Municipally Treated Waste Water",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Grey Water Reuse",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Nutrient Reduction",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Phosphorus & Ammonia Reduction",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 11,
        title: "Elimination of using Fresh Water in Industrial Applications",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 12,
        title: "Removal of Suspended Solids from Grey Water Reuse",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 13,
        title: "Promising RedOxy Technologies for Advance Potable Water Reuse",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 14,
        title: "RedOxy Treated Wastewater for Reuse in Industry, aquifer recharging and Irrigation",
        image: "/assets/img/menubar/product11.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  {
    id: 6,
    title: "Instant Products",
    children: [
      {
        id: 1,
        title: "Cooling System Water Treatment",
        image: "/assets/img/menubar/product12.png",
        description:
          "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 2,
        title: "Boiler Dosing Chemical",
        image: "/assets/img/menubar/product12.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 3,
        title: "Scale Prevention",
        image: "/assets/img/menubar/product12.png",
        description: "The world’s first premixed Water Intelligence Technology",
      },
      {
        id: 4,
        title: "Corrosion Prevention",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 5,
        title: "Antimicrobial Treatment",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 6,
        title: "Food & Water Industries",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 7,
        title: "Water Recycling Systems",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 8,
        title: "Aluminum",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 9,
        title: "Ammonia",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 10,
        title: "Arsenic",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 11,
        title: "Barium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 12,
        title: "Cadmium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 13,
        title: "Chloramine",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 14,
        title: "Chromium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 15,
        title: "Fluoride",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 16,
        title: "Bacteria & Viruses",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 17,
        title: "Lead",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 18,
        title: "Nirates",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 19,
        title: "Mercury",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 20,
        title: "Perchlorate",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 21,
        title: "Radium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 22,
        title: "Selenium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 23,
        title: "Silver",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 24,
        title: "Uranium",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 25,
        title: "Drinking Water Treatment",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 26,
        title: "Food & Water",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 27,
        title: "Water Reuse",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 28,
        title: "Point of Entry",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 29,
        title: "Roof Water for Entire Building",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 30,
        title: "Municipalities",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 31,
        title: "Water for Irrigation",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
      {
        id: 32,
        title: "Zero Liquid Discharge",
        image: "/assets/img/menubar/product12.png",
        description: "The world's first premixed Water Intelligence Technology",
      },
    ],
  },

  ];

export default ApplicationData;